name: Deploy PHP Site to IONOS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du dépôt
        uses: actions/checkout@v3

      - name: 🛡 Vérifier la présence de composer.lock
        run: |
          if [ ! -f composer.lock ]; then
            echo "❌ composer.lock est manquant. Veuillez le valider avant de pousser.";
            exit 1;
          fi

      - name: ⚡️ Mettre en cache les dépendances Composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 🧪 Installer les dépendances en local
        run: composer install --no-interaction --prefer-dist

      - name: 🔐 Configurer SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts

      - name: 🧪 Tester la connexion SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo '✅ Connexion SSH réussie'"

      - name: 📂 Déployer les fichiers sur IONOS
        run: |
          rsync -avz --delete --exclude-from=".rsync-ignore" -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_CHEMIN }}/${{ vars.DOSSIER_SITE_WEB }}

      - name: 📁 Lister les fichiers sur le serveur
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
            ls -la ${{ secrets.REMOTE_CHEMIN }}/${{ vars.DOSSIER_SITE_WEB }}/bin
          EOF

      - name: 📦 Installer les dépendances PHP sur le serveur
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_CHEMIN }}/${{ vars.DOSSIER_SITE_WEB }}
            php8.4-cli bin/composer install --no-interaction --prefer-dist --optimize-autoloader
          EOF

      # - name: 🔧 Ajuster les permissions (optionnel)
      #   run: |
      #     ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
      #       chmod -R 755 ${{ secrets.REMOTE_CHEMIN }}/${{ vars.DOSSIER_SITE_WEB }}
      #     EOF
